name: Package

on:
  workflow_dispatch:
  push:
    tags:
       - '*'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/mygento/deployer:v3
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1
        - name: Check Version
          run: sh check-version.sh
        - name: Download
          run: sh deb.sh
        - name: Results
          run: ls -lah .
        - name: Upload && Release
          run: sh release.sh
          env:
            SERVICE: ${{ secrets.SERVICE }}
            REALM: ${{ secrets.REALM }}
            REALM_LOGIN: ${{ secrets.REALM_LOGIN }}
            REALM_PASS: ${{ secrets.REALM_PASS }}
